### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by emanuelef** [cybertk/abao#54]
Hi,
I tried to install abad but I get: 

/usr/local/bin/abao -> /usr/local/lib/node_modules/abao/bin/abao
/usr/local/lib
└─┬ abao@0.3.1 
  ├── UNMET PEER DEPENDENCY chai@>= 2.0.0 < 3
  └─┬ request@2.65.0
    └── node-uuid@1.4.4 

npm WARN EPEERINVALID chai2-json-schema@1.2.0 requires a peer of chai@>= 2.0.0 < 3 but none was installed.

I used sudo npm install -g abao on a Mac,
thanks for any help

**Comment by ibruynin** [comment]
Same issue here: npm install -g abao
...
└─┬ abao@0.3.1
  └── UNMET PEER DEPENDENCY chai@>= 2.0.0 < 3

npm WARN EPEERINVALID chai2-json-schema@1.2.0 requires a peer of chai@>= 2.0.0 < 3 but none was installed.

Is there any temp workaround?

**Comment by cybertk** [comment]
Which npm version you guys used?

**Comment by emanuelef** [comment]
I'm using 3.3.12

**Comment by cybertk** [comment]
Try this ` npm install -g github:cybertk/abao#v0.4.0-beta.2`

**Comment by emanuelef** [comment]
Updated to nam 3.4.0, retried bu same error.

**Comment by emanuelef** [comment]
Hi,
retried with both and same error (now using npm 3.4.0):

$ sudo npm install -g github:cybertk/abao
/usr/local/bin/abao -> /usr/local/lib/node_modules/abao/bin/abao
/usr/local/lib
└─┬ abao@0.4.0-beta.2  (git://github.com/cybertk/abao.git#1f3e6510cb8c36f025ec5fe859ce33e60b8b1695)
  ├── UNMET PEER DEPENDENCY chai@>= 2.0.0 < 3
  └── fs@0.0.2

**Comment by ibruynin** [comment]
I use 3.3.6 and don't have git installed here yet.
Does it make sense to try it too or is emanuelef's response sufficient?

**Comment by cybertk** [comment]
It seems that **abao** does not support npm 3. Here is the output of npm v2.14.3

```
$ npm -g install abao
npm WARN peerDependencies The peer dependency chai@>= 2.0.0 < 3 included from chai2-json-schema will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by cybertk** [comment]
I added tests to coverage npm 3. **abao** is passed [all tests](https://travis-ci.org/cybertk/abao/jobs/91374817) on npm 3. It's so wired.

**Comment by ibruynin** [comment]
Hi - I tried installing 0.4.0-beta.2 as you suggested
npm WARN install Couldn't install optional dependency: shasum check failed for C:\xyz\Temp\npm-23152-cd8dbabd\registry.npmjs.org\csonschema\-\csonschema-0.5.2.tgz
npm WARN install Expected: 3d345a97bad5d767f40367550ec4418ab461c424
npm WARN install Actual:   03b361ad23457ac732b568218587a2d67c584aae
npm WARN install From:     https://registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz

**Comment by agsmorodin** [comment]
I am trying to install abao  and get the error:

npm install -g abao
/
|
npm ERR! Linux 3.10.0-229.el7.x86_64
npm ERR! argv "/opt/node-v4.2.2-linux-x64/bin/node" "/opt/node-v4.2.2-linux-x64/bin/npm" "install" "-g" "abao"
npm ERR! node v4.2.2
npm ERR! npm  v2.1.10

npm ERR! shasum check failed for /tmp/npm-23264-91729760/registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR! Expected: 3d345a97bad5d767f40367550ec4418ab461c424
npm ERR! Actual:   03b361ad23457ac732b568218587a2d67c584aae
npm ERR! From:     https://registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log

**Comment by thedrew12** [comment]
I'm getting the same error as above:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "github:cybertk/abao"
npm ERR! node v0.12.4
npm ERR! npm  v2.13.4

npm ERR! shasum check failed for /var/folders/zl/x4mr7wps1r329xqxcmqphmcm0000gp/T/npm-1341-6ed94d58/registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR! Expected: 3d345a97bad5d767f40367550ec4418ab461c424
npm ERR! Actual:   03b361ad23457ac732b568218587a2d67c584aae
npm ERR! From:     https://registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by BetaGrumm** [comment]
Getting the same bad checksum error as above:
```
sudo npm install -g abao
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "abao"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! shasum check failed for /tmp/npm-34869-95306ed7/registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR! Expected: 3d345a97bad5d767f40367550ec4418ab461c424
npm ERR! Actual:   03b361ad23457ac732b568218587a2d67c584aae
npm ERR! From:     https://registry.npmjs.org/csonschema/-/csonschema-0.5.2.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mkramer/Sites/sites-api/npm-debug.log
```

**Comment by BetaGrumm** [comment]
Ahh. After some digging, my issue is related to csonschema. I see there is already an issue open for it in that repo: https://github.com/cybertk/csonschema/issues/11

The npm package for csonschema is failing to install by itself, let alone as a dependency for abao.

**Comment by thedrew12** [comment]
I updated the package.json to the latest version for csonschema: 0.5.3-beta.1 and that seems to fix the issue in abao. After updating the version i can install it and run all the tests in abao.

**Comment by cybertk** [comment]
csonschema 0.5.3 has been published to npmjs.org. Could you try to install abao again?

**Comment by emanuelef** [comment]
Hi, I've just tried again but I still get:

$ sudo npm install -g abao
/usr/local/bin/abao -> /usr/local/lib/node_modules/abao/bin/abao
/usr/local/lib
└─┬ abao@0.3.1 
  └── UNMET PEER DEPENDENCY chai@>= 2.0.0 < 3

npm WARN EPEERINVALID chai2-json-schema@1.2.0 requires a peer of chai@>= 2.0.0 < 3 but none was installed.


Do I have to try with the beta ? Or is there any requirement to install chai separately ?
Thanks

**Comment by cybertk** [comment]
I removed the broken dep `chai2-json-schema`, please try with

```
npm install -g git://github.com/cybertk/abao.git#chai-json-schema
```

**Comment by emanuelef** [comment]
Thanks, now it has worked!

**Comment by ibruynin** [comment]
Works here as well.
Thanks a lot!
